.DEFAULT_GOAL := help

.PHONY: help install dev build lint

help:
	@echo Targets:
	@echo   make install   - Dependencies installieren (npm install)
	@echo   make dev       - Dev-Server starten (nuxt dev)
	@echo   make build     - Production-Build (nuxt build)
	@echo   make lint      - eslint

install:
	npm install

dev:
	npm run dev

build:
	npm run build

lint:
	npm run lint
